### ISSUE TITLE
Support for Current Table Formatting

### ISSUE THREAD

**Issue by Seraphendipity** [takumisoft68/vscode-markdown-table#10]
Instead of Format All Tables, Format Current Table, a la [Shuzo Iwasaki](https://github.com/shuGH)'s [popular extension](https://github.com/shuGH/vscode-table-formatter). There are times when I want to leave a previous table alone, or something that is not a table is formatted as a table.

This tool is otherwise really nice, being able to consolidate several table extensions down to one.

*Note: this is my first issue on another's project; if I'm approaching this wrong, please let me know.*

**Comment by takumisoft68** [comment]
@Seraphendipity Thank you for your issue report.

Your are bringing up two or three, I think.
Is my understanding correct?

1. (new comand) Navigate next/prev cell **without format**.
2. (additional) Suppprt other format pattern.
3. (bug) Not a table is foematted by mistake.

1. -> I will do it.
2. -> Please, show me a style of format, you need.
3. -> Please, show me anexample sentence to  reproduction.

**Comment by takumisoft68** [comment]
I added "(new comand) Navigate next/prev cell without format." in 0.4.1.

**Comment by takumisoft68** [comment]
@Seraphendipity Can I close this issue?
