### ISSUE TITLE
[Feature] delete row, delete column

### ISSUE THREAD

**Issue by shuaicj** [takumisoft68/vscode-markdown-table#14]

**Comment by takumisoft68** [comment]
Hi. @shuaicj .
There are useful vscode's vasic editor features!

Use box selection to select and delete column.
Use shift+delete to delete row.
https://code.visualstudio.com/docs/editor/codebasics#_column-box-selection

This extention does not implement features they can be done by vscode's basic features. It is policy of this extention.
