### ISSUE TITLE
compatible with a bit older version VSCode

### ISSUE THREAD

**Issue by shuaicj** [takumisoft68/vscode-markdown-table#15]
The plugin works perfect on my personal pc, but cannot be installed on my office pc with VSCode v1.44.2, which is released at 2020-04, and i can't upgrade it for some reasons. Is it possible to adapt the plugin to be compatible with not so up-to-date VSCode?

**Comment by takumisoft68** [comment]
@shuaicj maybe possible.

**Comment by takumisoft68** [comment]
Hi. @shuaicj 
I changed supported version to 1.40.0 or later from 1.50.0 or later.  
But I can't test to install on vscode 1.44.2.
I would be grateful if you would send me installation result for your office pc.

**Comment by shuaicj** [comment]
@takumisoft68 It works! Thanks a lot!
