### ISSUE TITLE
how to enable auto-format?

### ISSUE THREAD

**Issue by matthijsvk** [takumisoft68/vscode-markdown-table#16]
Hi,

this is a great extension :)
when I'm in a table and press Tab, a normal tab is inserted. Manually calling 'navigate to next cell' works.
In the documentation you wrote this only works with 'auto format'.
How do I enable this 'auto format' feature? Or could this be another issue?

**Comment by takumisoft68** [comment]
Hi, @matthijsvk. Thank you for using.

> In the documentation you wrote this only works with 'auto format'.  How do I enable this 'auto format' feature? Or could this be another issue?

It's a misunderstanding.

'navigate to next cell' command is assigned to Tab key.
But that keyboard shortcut is activated when only editing markdown file.
In some .txt/.log/... file or unsaved file, the shortcut is not functionally.

**Comment by matthijsvk** [comment]
Thanks!
I think it because of my settings; if I remove the "!suggestWidgetMultipleSuggestions && !suggestWidgetVisible", it works for me.
