### ISSUE TITLE
[compatibility] doesn't work well with "Markdown All in One" extension

### ISSUE THREAD

**Issue by AleksueiR** [takumisoft68/vscode-markdown-table#18]
Tabbing between cells doesn't work when the [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) extension is installed alongside. Turning its table auto-format option off doesn't seem to help.

VSCode Insiders: v1.54.0
Markdown All in One: v3.4.0
Markdown Table: v0.4.2

**Comment by GavinRay97** [comment]
Same issue here 😢

**Comment by takumisoft68** [comment]
@AleksueiR @GavinRay97 
It is conflicting of keybindings.
Remove or Change the "Markdown All in One" keybindings.

- conflicting commands
    - markdown.extension.onTabKey
    - markdown.extension.onShiftTabKey

1. Open "File -> Preference -> Keyboard Shortcuts".
2. Search as "markdown.extension tab".
3. Right click and "Remove Keybinding".

![image](https://user-images.githubusercontent.com/52767243/111794226-5b099e00-8909-11eb-8b63-a6bbd9c49c1a.png)

**Comment by rongcuid** [comment]
Would it not be much better if something can be added in the 'when' expression? This workaround would break other features like list indentation.

**Comment by takumisoft68** [comment]
@rongcuid 
I could not find a 'when' expression to prioritize this over "Markdown All in One".
Please tell me which expression is effective.

**Comment by rongcuid** [comment]
@takumisoft68 

I haven't worked with the extension, but what I meant is to enable this shortcut when the cursor is actually inside a table cell.

**Comment by takumisoft68** [comment]
@rongcuid 
Thanks for reply.

> when the cursor is actually inside a table cell.
Unfortunately, I can't find such an expression in vscode...

By the way, 'Ctrl + ]' and 'Ctrl + [' can be used for list indentation. FYI.

**Comment by GavinRay97** [comment]
Thank you for the reply, I must have missed it in my email earlier!

**Comment by mathesonphillip** [comment]
Thanks for the logging issue. I was able to work around using suggestions above.
Cheers

**Comment by aNickzz** [comment]
I have bound `ctrl+[` and `ctrl+]` to other commands since I prefer to use `tab` for indentation.

I agree with @rongcuid. Although there is no existing `when` clause for this, it is possible to create one with the [`setContext` api](https://code.visualstudio.com/api/references/when-clause-contexts#add-a-custom-when-clause-context). It should be possible to detect if the cursor is in a table whenever the cursor moves and update the context value.

I'll also raise this on the `yzhang.markdown-all-in-one` extension in case they have some ideas too.

**Comment by OldStarchy** [comment]
Looks like there's not much yzhang.markdown-all-in-one can do, the only way to do this might be creating a custom `when` clause.

**Comment by StephaneG31** [comment]
There's here : https://github.com/microsoft/vscode/issues/134544#issuecomment-937615186 and explanation of what this extension can change to improve that point.

**Comment by takumisoft68** [comment]
I resolved that confliction.
I send a pull request at https://github.com/yzhang-gh/vscode-markdown/pull/1075.

**Comment by takumisoft68** [comment]
I resolved that confliction.
I send a pull request to yzhang-gh/vscode-markdown at 1075.

**Comment by takumisoft68** [comment]
I resolved this confliction.

v0.8.0 had been released.
And I send a pull request to yzhang-gh/vscode-markdown at 1075.

**Comment by takumisoft68** [comment]
Keep open until pull request yzhang-gh/vscode-markdown 1075 will be closed.

**Comment by chraxo** [comment]
Thanks for you efforts to find a proper solution. For now I found the following workaround. It's not a super-nice solution, but at it least works. Maybe the solution is obvious to some of you, but for me this was new, so this information might help also other people:

It seems that the context keys of `markdowntable` are usable within the `when` condition for other extensions as well. So the desired behavior can be achieved by extending the `when` conditions of the following commands with `&& !markdowntable.contextkey.selection.InMarkdownTable`: 
* `markdown.extension.onTabKey`
* `markdown.extension.onShiftTabKey`

The full settings then look like this:

```
{
  "key": "tab",
  "command": "markdown.extension.onTabKey",
  "when": "editorTextFocus && !editorHasMultipleSelections && !editorReadonly && !editorTabMovesFocus && !hasOtherSuggestions && !hasSnippetCompletions && !inSnippetMode && !inlineSuggestionVisible && !markdowntable.contextkey.selection.InMarkdownTable && !suggestWidgetVisible && editorLangId == 'markdown'"
}
```
```
{
  "key": "shift+tab",
  "command": "markdown.extension.onShiftTabKey",
  "when": "editorTextFocus && !editorHasMultipleSelections && !editorReadonly && !editorTabMovesFocus && !hasOtherSuggestions && !hasSnippetCompletions && !inSnippetMode && !markdowntable.contextkey.selection.InMarkdownTable && !suggestWidgetVisible && editorLangId == 'markdown'"
}
```

**Comment by yiufung** [comment]
@chraxo This is a very good workaround. Thanks.

**Comment by hpigot** [comment]
@chraxo worked for me as well. Thanks. Perhaps this can be added to the extension as a fix for this issue.

**Comment by takumisoft68** [comment]
@AleksueiR @GavinRay97 @rongcuid @mathesonphillip @OldStarchy @StephaneG31 @chraxo @yiufung @hpigot 
I’m glad to say that we got compatibility between "Markdown All in One".
My pull request has been merged. And v3.4.4 is released.

Update your "Markdown All in One" to v3.4.4.
It is important to note, however, that v3.4.4 is still pre-release version.
