### ISSUE TITLE
`Tab` shortcut key not works in MacOS

### ISSUE THREAD

**Issue by alterhu2020** [takumisoft68/vscode-markdown-table#21]
Hi @takumisoft68 ,
Thanks for working this plugin living, which helps save our time. But when I use it in my MacOS machine,  and type the `tab` shortcut key to quick create table, but it doesn't work, have you notice this issue? 

thanks.

**Comment by takumisoft68** [comment]
@alterhu2020 
sorry.
I don't have Mac. I haven't tested it on Mac OS.
I have no idea.

**Comment by ztatlock** [comment]
FWIW, the `Tab` shortcut does work for me in macOS. @alterhu2020 it maybe worth [inspecting your current VSCode shortcuts](https://code.visualstudio.com/docs/getstarted/keybindings) to see if something is disabled or conflicting.

**Comment by cmoesel** [comment]
For me, it was actually #18 that was causing the problem...

**Comment by takumisoft68** [comment]
#18 has been closed.
