### ISSUE TITLE
Emoji length leads to alignment issues.

### ISSUE THREAD

**Issue by ztatlock** [takumisoft68/vscode-markdown-table#22]
Many thanks for the excellent extension!

One issue I have noticed is that alignment does not take into account multi-character sequences like emojis:

```
| C1          | C2        |
| ----------- | --------- |
| 🧪        | Some text |
| Another row | More text |
```

Any advice on how to work around this issue would be much appreciated. Thanks again for the great work!!

**Comment by takumisoft68** [comment]
@ztatlock 
Thank you for using this extension.

I have fixed up handling of zenkaku at 0.5.2.
However, most emoji doesn't have coordinated width in most monospaced fonts.
So alignment still be slipped. Sorry...
