### ISSUE TITLE
Open VSX

### ISSUE THREAD

**Issue by noraj** [takumisoft68/vscode-markdown-table#26]
Hi can you push your extension to https://open-vsx.org/ in addition to VSCode Market Place so people using the FLOSS version could install it too?

I wrote [an article](https://blog.raw.pm/en/FLOSS-version-of-vscode-and-extensions-gallery/) on the subject.

**Comment by takumisoft68** [comment]
@noraj 
I published this extension to open vsx registory.
https://open-vsx.org/extension/TakumiI/markdowntable

**Comment by noraj** [comment]
![image](https://user-images.githubusercontent.com/16578570/122076963-9c6ff380-cdfb-11eb-924f-27692174bf73.png)

You can claim the namespace: https://github.com/eclipse/openvsx/wiki/Namespace-Access

**Comment by takumisoft68** [comment]
I have already claimed.
https://github.com/EclipseFdn/open-vsx.org/issues/545

**Comment by takumisoft68** [comment]
I have already claimed.
https://github.com/EclipseFdn/open-vsx.org/issues/545

**Comment by fgimian** [comment]
@takumisoft68 Hey there, I noticed the version of the extension on OpenVSX is older than the one in the Visual Studio Code marketplace. When you have a free moment, would you mind updating the version on OpenVSX please?

Thanks heaps
Fotis
