### ISSUE TITLE
Missing whitespace when formatting table containing "umlauts"

### ISSUE THREAD

**Issue by McJackson164** [takumisoft68/vscode-markdown-table#3]
**Issue:**
When formatting a table containing "umlauts" like ä or ö, the row containing the umlaut is missing a whitespace.

**Expected output:**
```
| EN     | DE     |
| ------ | ------ |
| Apple  | Apfel  |
| Apples | Äpfel  |
| Banana | Banane |
```

**Real output:**
```
| EN     | DE     |
| ------ | ------ |
| Apple  | Apfel  |
| Apples | Äpfel |
| Banana | Banane |
```

**Reproduce:**
Format the following markdown table using CTRL+ALT+F
```
|EN|DE|
|-|-|
|Apple|Apfel|
|Apples|Äpfel|
|Banana|Banane|
```

**Comment by takumisoft68** [comment]
@McJackson164 Thank you for your issue report & kindly reproduction.
I’m not sure if I can make it work because I'am japanese and not used to "umlauts".
But I will go for it.
