### ISSUE TITLE
Indentation disappears when formating table

### ISSUE THREAD

**Issue by takumisoft68** [takumisoft68/vscode-markdown-table#4]
Keep indentation

**Comment by ctf0** [comment]
b4 pressing tab we need to check if we are inside a table or not.

**Comment by ctf0** [comment]
@takumisoft68 can we also have `shift+tab` to go to prev cell ?

**Comment by takumisoft68** [comment]
@ctf0 Do you say another issue?

**Comment by ctf0** [comment]
more of a feature really.

**Comment by takumisoft68** [comment]
@ctf0 Thanks for a new idea.
But this ticket is not an idea inventry.
New idea needs a new ticket, so I have created another ticket #5.
