### ISSUE TITLE
CSV support request

### ISSUE THREAD

**Issue by T3sT3ro** [takumisoft68/vscode-markdown-table#46]
Could you please add support to create the table from csv data? Or even better a setting to use possible delimiters regex.

**Comment by takumisoft68** [comment]
@T3sT3ro Thank ypu for your feedback.

It is not difficult.
But I'm careful to adding one more context menu.
Because this extension already has so many menus that it is nearly out of screen.

F.Y.I.
There are good extensions for convert csv to md table in marketplace.

**Comment by lacek** [comment]
Would it be possible to detect the delimiter based on the current language mode (`document. languageId`) VS code is in, and fall back to origin tsv parsing when detection fails?

I found Rainbow CSV to support similar feature: https://github.com/mechatroner/vscode_rainbow_csv/tree/b5b423d8904b2a8f687c6ca4857dccf2d5c9917e#supported-separators.

In this way, there is no need to add more item to the context menu. Users needing for conversion can simply open a new editor tab, paste the TSV/CSV content, set the desired language mode that matches the delimiter and invoke TSV to table of this extension.

**Comment by takumisoft68** [comment]
Resolved in 0.11.0
