### ISSUE TITLE
Shift + Alt +F conflicts with the vscode's format command

### ISSUE THREAD

**Issue by snyang** [takumisoft68/vscode-markdown-table#49]
`Shift` + `Alt` +`F` conflicts with the vscode's format command.
The problem leads me cannot format the markdown document by using the shortcut key.

**Comment by tjx666** [comment]
https://github.com/prettier/prettier-vscode/issues/2655

**Comment by takumisoft68** [comment]
ok.
I plan to remove this key binding.

**Comment by takumisoft68** [comment]
Key binding "Shift + Alt + F" is removed at v0.10.1
