### ISSUE TITLE
Certain commands do not work well with cells selected

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [takumisoft68/vscode-markdown-table#50]
When you run the following two commands with the text in the cell selected, it doesn't work.

- `markdowntable.insertRight`
- `markdowntable.insertLeft`

## To reproduce

The keybindings for the commands to insert columns left and right are defined as follows. The When clause is based on the package.json below.

https://github.com/takumisoft68/vscode-markdown-table/blob/465bb110dc64213f59a67a29868a2e323531e637/package.json#L84

```json
    {
        "key": "alt+shift+r",
        "command": "markdowntable.insertRight",
        "when": "editorTextFocus && !editorReadonly && !editorTabMovesFocus && !inSnippetMode && !suggestWidgetMultipleSuggestions && !suggestWidgetVisible && editorLangId == 'markdown' && markdowntable.contextkey.selection.InMarkdownTable",
    },
    {
        "key": "alt+shift+l",
        "command": "markdowntable.insertLeft",
        "when": "editorTextFocus && !editorReadonly && !editorTabMovesFocus && !inSnippetMode && !suggestWidgetMultipleSuggestions && !suggestWidgetVisible && editorLangId == 'markdown' && markdowntable.contextkey.selection.InMarkdownTable",
    },
```

Currently, if you use `Tab` or `Shift+Tab` to move a cell, the cell you moved to will be selected. If you execute the above keybinding (e.g. `Alt+Shift+R`) in this state, the following popup message will be displayed. Also, it does not work well.

```
Markdown Table : Insert command doesn't allowed range selection.

Source: Markdwon Table (Extension)
```

If you run the keybindings with no cell selected it works fine.

## What is required

I want to execute a command to insert a column even when a cell is selected.

## Version

- Markdown Table: 0.10.1
- VS Code:

    ```
     Version: 1.70.1 (user setup)
      Commit: 6d9b74a70ca9c7733b29f0456fd8195364076dda
        Date: 2022-08-10T06:08:33.642Z
    Electron: 18.3.5
    Chromium: 100.0.4896.160
     Node.js: 16.13.2
          V8: 10.0.139.17-electron.0
          OS: Windows_NT x64 10.0.22000
    ```

**Comment by takumisoft68** [comment]
In v0.10.2 or later, insert commands allow selecting range.

**Comment by Yarakashi-Kikohshi** [comment]
It now wors without any problems. Thank you so much for the update. 😄
