### ISSUE TITLE
Support Quarto Markdown files

### ISSUE THREAD

**Issue by MRosenbauer** [takumisoft68/vscode-markdown-table#53]
Similiar to #24 we have the same issue with `.qmd` files.
[Quarto](https://quarto.org/) is a rather new framework to embed python and R code in Markdown.
Overwriting the file association like in #24 mentioned erases the support for all Quarto-Markdown features, which is obviously not optimal.

Would it be possible to also support the `.qmd` file-type? 

Thank you for your time!

**Comment by takumisoft68** [comment]
@MRosenbauer 
Quarto support is added at 0.10.4.

It requires Quarto extension.
