### ISSUE TITLE
Feature request: command to rearrange column order

### ISSUE THREAD

**Issue by jmoore34** [takumisoft68/vscode-markdown-table#54]
It would be nice to have a command to swap a column with the column to the left or right of it.

E.g. if you had your cursor in the Age column:

| First Name | Age | Last Name |
| ---------- | --- | --------- |
| John       | 34  | Doe       |
| Ronnie     | 40  | Lee       |

and did `Markdown Table: Swap column with column to the right`, you would get:

| First Name | Last Name | Age |
| ---------- | --------- | --- |
| John       | Doe       | 34  |
| Ronnie     | Lee       | 40  |

**Comment by takumisoft68** [comment]
Resoleved in 0.11.0
