### ISSUE TITLE
Whether extension works in local environment or not

### ISSUE THREAD

**Issue by mekua-jp** [takumisoft68/vscode-markdown-table#62]
Hello. I’m wiring to you to confirm whether this extension can work without importing/exporting libraries or codes.

Our team has limitations that “Do not transmit data with any server in Internet” except for installing extension itself or visit website with users intention. As I searched repository, there seems no track about importing/exporting. This extension works alone, right?

Regards.

**Comment by takumisoft68** [comment]
@mekua-jp 
Yes. This extention works alone.

**Comment by mekua-jp** [comment]
Thanks.
