### ISSUE TITLE
Add support for pandoc grid tables

### ISSUE THREAD

**Issue by AH-Hammi** [takumisoft68/vscode-markdown-table#63]
https://pandoc.org/chunkedhtml-demo/8.9-tables.html

It would be very nice to have support for the pandoc grid tables because they give a lot more flexibility in creating tables in Markdown

**Comment by takumisoft68** [comment]
Sorry. I can't accept your request. 
It is out of markdown syntax spec. 
This extension has a policy to not enhance or change markdown spec.
