### ISSUE TITLE
Feature Request: Align Left, Center, Right

### ISSUE THREAD

**Issue by gitbjo** [takumisoft68/vscode-markdown-table#9]
Hi,

would be nice having a way to change alignment of a column and have it reflected in the table.

Use Case:

1. Paste a TSV table
2. Convert to MD Table
would format by default left (as today), **except** if data is numeric, then align right
3. put cursor in a column, select drop-down (or key shortcut) "Markdown Table: Align Left|Center|Right"
This would change the alignment marker in the header separator and align the data as requested.

I think it's would be useful for most of your users.
Thanks for the great work and sharing  👍 
Björn

**Comment by takumisoft68** [comment]
fix in 7c5fef36

**Comment by takumisoft68** [comment]
Hi, @gitbjo 

I have released ver. 0.3.1 in vscode marketplace.
Please try it.

I hope you like it.
